server:
  port: 8765
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB

#############################################
#
#   配置数据源
#
#############################################
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/east_north_boot?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: 123456a?
    hikari:
      connection-timeout: 30000             # 等待连接池分配连接的最大时长（毫秒）
      minimum-idle: 5                       # 最小连接数
      maximum-pool-size: 20                 # 最大连接数
      auto-commit: true                     # 自动提交
      idle-timeout: 600000                  # 连接超时的最大时长（毫秒）
      pool-name: DateSourceHikariCP         # 连接池名字
      max-lifetime: 1800000                 # 连接的生命时长（毫秒）
      connection-test-query: SELECT 1

#############################################
#
#   mybatis配置
#
#############################################
mybatis:
  type-aliases-package: com.eastnorth.pojo  # 所有POJO类所在包路径
  mapper-locations: classpath:mapper/*.xml  # mapper映射文件

#############################################
#
#   mybatis mapper 配置
#
#############################################
#   通用 mapper 配置
mapper:
  mappers: com.eastnorth.my.mapper.MyMapper
  not-empty: false                          # 在进行数据库操作的时候，判断表达式 username != null, 是否追加 username != ''
  identity: MYSQL